FROM ruby:3.1

# Install system libs required by Canvas
RUN apt-get update && apt-get install -y \
  build-essential \
  libxml2-dev \
  libxmlsec1-dev \
  libxmlsec1-openssl \
  libpq-dev \
  nodejs npm \
  yarn \
  && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy files
COPY . .

# Install Ruby gems
RUN gem install bundler -v 2.5.10
RUN bundle install

# Install JS deps
RUN yarn install --pure-lockfile

# Compile Canvas assets
RUN bundle exec rails canvas:compile_assets

# Rails environment
ENV RAILS_ENV=production

# Render sets $PORT automatically
CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0", "-p", "3000"]
